[package]
name = "railslens"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
color-eyre = "0.6.3"
colored = "2.1.0"
crossterm = "0.28.1"
derive_setters = "0.1.6"
ratatui = "0.28.1"
regex = "1.11.0"
textwrap = "0.16.1"
